@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "API_KEY=%~1"
if not defined OPENROUTER_ENV set "OPENROUTER_ENV=%USERPROFILE%\.config\mini-swe-agent\.env.openrouter"
set "OPENROUTER_BASE_URL=https://openrouter.ai/api/v1"

echo.
echo ==========================================
echo   OpenRouter Setup for AI Agent
echo ==========================================
echo.

if not defined API_KEY (
    echo Get your API key from: https://openrouter.ai/keys
    set /p "API_KEY=Enter your OpenRouter API key: "
)

if not defined API_KEY (
    echo ERR No API key provided
    exit /b 1
)

echo -- Testing API key...
set "TEST_MODEL=meta-llama/llama-3.2-3b-instruct:free"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$body=@{model=$env:TEST_MODEL;messages=@(@{role='user';content='Say hello in one word.'});max_tokens=10}|ConvertTo-Json -Depth 5; try { Invoke-WebRequest -Uri ($env:OPENROUTER_BASE_URL + '/chat/completions') -Method Post -Headers @{Authorization=('Bearer ' + $env:API_KEY);'HTTP-Referer'='https://github.com/ai-lives-on-computer';'X-Title'='AI-Lives-On-Computer'} -ContentType 'application/json' -Body $body -TimeoutSec 30 | Out-Null; exit 0 } catch { Write-Host $_.Exception.Message; exit 1 }"
if errorlevel 1 (
    echo ERR API key validation failed
    exit /b 1
)

for %%I in ("%OPENROUTER_ENV%") do if not exist "%%~dpI" mkdir "%%~dpI"
(
    echo # OpenRouter Configuration for AI Agent
    echo # Generated by setup-openrouter.bat on %DATE% %TIME%
    echo.
    echo OPENAI_API_KEY=%API_KEY%
    echo OPENAI_BASE_URL=%OPENROUTER_BASE_URL%
    echo MSWEA_MODEL_NAME=openai/meta-llama/llama-3.3-70b-instruct
    echo MSWEA_CONFIGURED=true
    echo MSWEA_COST_TRACKING=ignore_errors
) > "%OPENROUTER_ENV%"

echo OK Configuration saved
echo Run: run_ai.bat openrouter
